#! /bin/bash
set -e
# default CCACHE_DIR is ../.ccache which is inside source (and will get cleaned)
export CCACHE_DIR="../../.ccache"
mkdir -p build
cd build
cmake .. -DODROID=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo; make -j$(nproc)


