#! /bin/bash
set -e
echo "box86 packaging"
cp source/build/box86 pkg/

mkdir -p pkg/lib
cp /lib/i386-linux-gnu/libgcc_s.so.1 pkg/lib
cp /usr/lib/i386-linux-gnu/libstdc++.so.5 pkg/lib
cp /usr/lib/i386-linux-gnu/libstdc++.so.6 pkg/lib

mkdir -p pkg/native
cp /usr/lib/arm-linux-gnueabihf/libEGL.so.1 pkg/native
cp /usr/lib/arm-linux-gnueabihf/libGL.so.1 pkg/native